### Association Rule Minning

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
transactions=[
    ['Bread','Chese','Egg','Juice'],
    ['Bread','Chese','Juice'],
    ['Bread','Milk','Youghurt'],
    ['Bread','Milk','Juice'],
    ['Milk','Chese','Juice']
]

In [10]:
transactions2=[
    ['E','A','D','B'],
    ['D','A','C','B','E'],
    ['C','A','B','A'],
    ['B','A','D'],
    ['D'],
    ['D','B'],
    ['A','D','E'],
    ['B','C']
]

### Preprocess the Data

In [12]:
#Encode the Transactions
from mlxtend.preprocessing import TransactionEncoder
encoder = TransactionEncoder()
encoded_Transaction = encoder.fit(transactions2).transform(transactions2)
#create the data frame from the encoded Transaction

In [13]:
df=pd.DataFrame(encoded_Transaction,columns=encoder.columns_)
df

       A      B      C      D      E
0   True   True  False   True   True
1   True   True   True   True   True
2   True   True   True  False  False
3   True   True  False   True  False
4  False  False  False   True  False
5  False   True  False   True  False
6   True  False  False   True   True
7  False   True   True  False  False

### Find the Rules

In [14]:
from mlxtend.frequent_patterns import fpgrowth
fpgrowth(df,use_colnames=True)

   support itemsets
0    0.750      (D)
1    0.750      (B)
2    0.625      (A)
3    0.500   (D, B)
4    0.500   (A, B)
5    0.500   (A, D)

In [15]:
from mlxtend.frequent_patterns import apriori
apriori(df,use_colnames=True)

   support itemsets
0    0.625      (A)
1    0.750      (B)
2    0.750      (D)
3    0.500   (A, B)
4    0.500   (A, D)
5    0.500   (D, B)