In [2]:
import pandas as pd

In [3]:
#read csv files
df = pd.read_csv("sample_10_records.csv")
df

   ID    Name  Age       City
0   1   Aarav   21       Pune
1   2    Diya   22     Mumbai
2   3   Rohan   20      Delhi
3   4   Sneha   23  Bengaluru
4   5   Karan   24  Hyderabad
5   6   Priya   21    Chennai
6   7  Vikram   25    Kolkata
7   8  Ananya   22     Jaipur
8   9   Rahul   23  Ahmedabad
9  10   Meera   20     Nagpur

In [4]:
# read json files
df = pd.read_json("sample_10_records.json")
df

   ID    Name  Age       City
0   1   Aarav   21       Pune
1   2    Diya   22     Mumbai
2   3   Rohan   20      Delhi
3   4   Sneha   23  Bengaluru
4   5   Karan   24  Hyderabad
5   6   Priya   21    Chennai
6   7  Vikram   25    Kolkata
7   8  Ananya   22     Jaipur
8   9   Rahul   23  Ahmedabad
9  10   Meera   20     Nagpur

In [10]:
print(df.head())
print()
print(df.head(2))
print()
print(df.tail())
print()
print(df.tail(3))
print()

   ID   Name  Age       City
0   1  Aarav   21       Pune
1   2   Diya   22     Mumbai
2   3  Rohan   20      Delhi
3   4  Sneha   23  Bengaluru
4   5  Karan   24  Hyderabad

   ID   Name  Age    City
0   1  Aarav   21    Pune
1   2   Diya   22  Mumbai

   ID    Name  Age       City
5   6   Priya   21    Chennai
6   7  Vikram   25    Kolkata
7   8  Ananya   22     Jaipur
8   9   Rahul   23  Ahmedabad
9  10   Meera   20     Nagpur

   ID    Name  Age       City
7   8  Ananya   22     Jaipur
8   9   Rahul   23  Ahmedabad
9  10   Meera   20     Nagpur

In [12]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      10 non-null     int64
 1   Name    10 non-null     object
 2   Age     10 non-null     int64
 3   City    10 non-null     object
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes
None

In [15]:
print(df.shape)

(10, 4)

In [17]:
print(df.describe())

             ID       Age
count  10.00000  10.00000
mean    5.50000  22.10000
std     3.02765   1.66333
min     1.00000  20.00000
25%     3.25000  21.00000
50%     5.50000  22.00000
75%     7.75000  23.00000
max    10.00000  25.00000

In [22]:
print(df.columns)

Index(['ID', 'Name', 'Age', 'City'], dtype='object')

In [23]:
print(df.nunique())

ID      10
Name    10
Age      6
City    10
dtype: int64