In [2]:
import pandas as pd

In [2]:
df = pd.read_csv("globalAirQuality.csv")
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [3]:
#Acsses data by columns
print(df["city"].nunique())
print(df[["city","aqi"]])

50
           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [4]:
#Acsses data by rows
print(df.loc[0])
print(df.loc[0:2])

timestamp      2025-11-04 18:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               50.295
pm10                              108.938
no2                                27.998
so2                                 6.539
o3                                 52.568
co                                  1.096
aqi                                   108
temperature                        18.504
humidity                           70.168
wind_speed                          3.725
Name: 0, dtype: object
                    timestamp country      city  latitude  longitude    pm25  \
0  2025-11-04 18:25:17.554219      US  New York    40.713    -74.006  50.295
1  2025-11-04 19:25:17.554219      US  New York    40.713    -74.006  32.083
2  2025-11-04 20:25:17.554219      US  New York    40.713    -74.006  42.250

      pm10     no2    so2      o3     co  aqi  temperature  humidity  \
0  108.938  27.998  6.539  52.568  1.096  108       18.504    70.168
1   63.043  36.120  4.021  43.536  1.075   90        5.838    80.088
2   82.553  26.935  9.538  23.320  0.977   84       31.833    62.783

   wind_speed
0       3.725
1       8.969
2       9.650

In [5]:
print(df.iloc[0,:3])

timestamp    2025-11-04 18:25:17.554219
country                              US
city                           New York
Name: 0, dtype: object

In [6]:
print(df.loc[0,"city"])

New York

In [7]:
print(df.iloc[0:2,1:3])

  country      city
0      US  New York
1      US  New York

In [8]:
print(df.iat[0,2])

New York

In [9]:
print(df.at[0,"city"])

New York

***Transformation***

In [10]:
df = pd.read_csv("employee_data.csv")
df2 = df.copy()
df["tax"] = df2["Salary"].apply(lambda x:"20%"if x>=50000 else "10%")
df

   ID     Name  Age Department  Salary  tax
0   1    Alice   25         HR   55000  20%
1   2      Bob   32         IT   72000  20%
2   3  Charlie   28    Finance   48000  10%
3   4    David   45  Marketing   91000  20%
4   5      Eva   38         IT   65000  20%
5   6    Frank   29    Finance   50000  20%
6   7    Grace   41         HR   82000  20%
7   8   Hannah   26  Marketing   47000  10%
8   9      Ian   35         IT   75000  20%
9  10    Julia   30    Finance   60000  20%

In [11]:
#assign
df2.assign(new_income = df2["Salary"]*1.1)

   ID     Name  Age Department  Salary  new_income
0   1    Alice   25         HR   55000     60500.0
1   2      Bob   32         IT   72000     79200.0
2   3  Charlie   28    Finance   48000     52800.0
3   4    David   45  Marketing   91000    100100.0
4   5      Eva   38         IT   65000     71500.0
5   6    Frank   29    Finance   50000     55000.0
6   7    Grace   41         HR   82000     90200.0
7   8   Hannah   26  Marketing   47000     51700.0
8   9      Ian   35         IT   75000     82500.0
9  10    Julia   30    Finance   60000     66000.0

In [12]:
#replace
df2["Department"] =df2["Department"].replace("H R","HeadR")
df2

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [13]:
df2.rename(columns={"Salary":"Income"})

   ID     Name  Age Department  Income
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [22]:
df2 = df.copy()
new_col_order = list(df.columns)
new_col_order.remove('ID')
new_col_order.append('ID')
new_col_order
df2[new_col_order]

      Name  Age Department  Salary  tax  ID
0    Alice   25         HR   55000  20%   1
1      Bob   32         IT   72000  20%   2
2  Charlie   28    Finance   48000  10%   3
3    David   45  Marketing   91000  20%   4
4      Eva   38         IT   65000  20%   5
5    Frank   29    Finance   50000  20%   6
6    Grace   41         HR   82000  20%   7
7   Hannah   26  Marketing   47000  10%   8
8      Ian   35         IT   75000  20%   9
9    Julia   30    Finance   60000  20%  10

In [32]:
df2 = df.copy()
df2 = df2.drop_duplicates() 
df2.fillna(0)
df2=df2.sort_values("Salary")
df2.reset_index(drop = True)
df2.to_csv("Sorted_Data")

In [34]:
df2.groupby("Department")["Salary"].mean()
df2.groupby("Department")["Salary"].min()

Department
Finance      48000
HR           55000
IT           65000
Marketing    47000
Name: Salary, dtype: int64

In [38]:
df2.groupby("Department")["Salary"].agg(avg_sal="mean",max_sal="max",min_sal="min")

                 avg_sal  max_sal  min_sal
Department
Finance     52666.666667    60000    48000
HR          68500.000000    82000    55000
IT          70666.666667    75000    65000
Marketing   69000.000000    91000    47000

In [39]:
df2.groupby("Department").agg({
    "Salary":"mean",
    "Age":"min"
})

                  Salary  Age
Department
Finance     52666.666667   28
HR          68500.000000   25
IT          70666.666667   32
Marketing   69000.000000   26

In [ ]:
df2.groupby("Department").agg(
    max_sal = ("Salary":"mean"),
    "Age":"min"
)

In [7]:
df=pd.DataFrame({
    "country":["USA","USA","India","India"],
    "year":[2020,2021,2020,2021],
    "sales":[100,120,90,110],
    "profit":[20,25,18,22],
    "tax":[10,20,30,20]
})
df.melt(
    id_vars = ["country","year"],
    value_vars =["sales","profit","tax"],
    var_name="matrics",
    value_name = "value"
)

   country  year matrics  value
0      USA  2020   sales    100
1      USA  2021   sales    120
2    India  2020   sales     90
3    India  2021   sales    110
4      USA  2020  profit     20
5      USA  2021  profit     25
6    India  2020  profit     18
7    India  2021  profit     22
8      USA  2020     tax     10
9      USA  2021     tax     20
10   India  2020     tax     30
11   India  2021     tax     20

In [6]:
df

  country  year  sales  profit  tax
0     USA  2020    100      20   10
1     USA  2021    120      25   20
2   India  2020     90      18   30
3   India  2021    110      22   20