In [1]:
import pandas as pd

In [2]:
info={
    "Name" : ["Shiva","Om","Syoug","Tejas"],
    "CGPA" : [7.0,9.0,8.5,8.7]
}
df = pd.DataFrame(info)
print(df)

    Name  CGPA
0  Shiva   7.0
1     Om   9.0
2  Syoug   8.5
3  Tejas   8.7

In [3]:
df

    Name  CGPA
0  Shiva   7.0
1     Om   9.0
2  Syoug   8.5
3  Tejas   8.7

Series

In [4]:
s = pd.Series([1,2,3,4,5])
print(s)
print(type(s))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [5]:
#index
print(s[0])
print(s[1])

1
2

In [6]:
s = pd.Series([11,25,30,41,50,"abc"],index=["Shiva","Om","Syoug","Tejas","Alice",123])
print(s)
print(s["Shiva"])
print(s.iloc[0])
print(s.index)

Shiva     11
Om        25
Syoug     30
Tejas     41
Alice     50
123      abc
dtype: object
11
11
Index(['Shiva', 'Om', 'Syoug', 'Tejas', 'Alice', 123], dtype='object')

In [7]:
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([10,20,30,40,50])
print(s1+s2)
s1[0]=100
print(s1+s2)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    110
1     22
2     33
3     44
4     55
dtype: int64

In [8]:
change = s1.drop(0)
print(change)

1    2
2    3
3    4
4    5
dtype: int64

In [9]:
# type 1 create dataframe  Dictonary to list
info={
    "Name":["Shiva","Om","Syoug","Tejas"],
    "Age":[21,22,21,25],
    "GPA":[9,8.5,5.7,0]
}
df=pd.DataFrame(info)
df

    Name  Age  GPA
0  Shiva   21  9.0
1     Om   22  8.5
2  Syoug   21  5.7
3  Tejas   25  0.0

In [10]:
#Type 2 of dataframe -> List to List
df_1 = pd.DataFrame([["Shiva",21],["Om",23]],columns=["Name","AGE"])
df_1

    Name  AGE
0  Shiva   21
1     Om   23

In [12]:
#type 3 creating dataframe ->
import numpy as np
np_arr = np.array([[1,2,3,],[4,5,6]])
df_2 = pd.DataFrame(np_arr,columns=["A","B","C"])
df_2

   A  B  C
0  1  2  3
1  4  5  6